/*
 * quickjs-aot.h — TNR AOT twin contract (fork patch; threejs-native-runtime plan §5.3)
 *
 * The contract between quickjs (this fork), C code GENERATED by tnr-aotc ("twins"),
 * and tnr-aotc itself. Twins replay the interpreter's dispatch loop for one
 * function's opcode sequence: the operand stack and locals are a fixed C array,
 * jumps are C gotos, and every non-trivial opcode calls a JS_AOTOp* helper below
 * whose body is the interpreter case body — same semantics, no dispatch.
 *
 * Ground rules for generated code (tnr-aotc enforces them):
 *  - Atom and cpool OPERANDS are read from the runtime JSFunctionBytecode the twin
 *    is attached to (JS_AOTAtom on the live byte stream / JS_AOTCpool) — atom
 *    indices are process-local, so they can never be baked into the C text.
 *  - Every helper that can throw takes `next_pc` (the interpreter's pc AFTER the
 *    current instruction) and stores it in the frame first, so stack traces and
 *    pc2line stay exact.
 *  - On helper failure (-1 / JS_EXCEPTION) the twin jumps to its exception block:
 *    free live stack values, JS_AOTFrameLeave, return JS_EXCEPTION — the same
 *    unwind the interpreter performs. Twins never contain try/catch (functions
 *    with OP_catch/OP_gosub are not translated in v1).
 *
 * This header is also the ONLY thing generated code #includes (it pulls quickjs.h).
 */
#ifndef QUICKJS_AOT_H
#define QUICKJS_AOT_H

#include <string.h>
#include "quickjs.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Opcode numbering mirror — numerically identical to the interpreter's internal
   OPCodeEnum by construction (same x-macro header, same order). Generated code
   passes these to the JS_AOTOp* helpers that take an `int op`. */
enum {
#define FMT(f)
#define DEF(id, size, n_pop, n_push, f) JS_AOT_OP_ ## id,
#define def(id, size, n_pop, n_push, f)
#include "quickjs-opcode.h"
#undef def
#undef DEF
#undef FMT
    JS_AOT_OP_COUNT,
};

/* ---- stack frame ------------------------------------------------------------------
   Twins stack-allocate an opaque frame blob; quickjs.c static_asserts that
   sizeof(JSStackFrame) fits. Bump JS_AOT_FRAME_SIZE if the assert ever fires. */
#if defined(__GNUC__) || defined(__clang__)
#define TNR_AOT_FLATTEN __attribute__((flatten))
#else
#define TNR_AOT_FLATTEN
#endif

#define JS_AOT_FRAME_SIZE 128
typedef struct JSAOTFrame {
    union {
        void *align_;
        unsigned char opaque[JS_AOT_FRAME_SIZE];
    } u;
} JSAOTFrame;

/* Replicates JS_CallInternal's prologue for a bytecode function: stack-overflow
   check, argument copy into `locals` (always copied — twins use a fixed layout
   locals[arg_count + var_count + stack_size]), locals initialized to undefined,
   frame pushed, realm selected. Returns the realm context to run under, or NULL
   with an exception pending on the caller context. `frame_var_refs` must hold
   var_ref_count slots (pass NULL when var_ref_count is 0). */
JS_EXTERN JSContext *JS_AOTFrameEnter(JSContext *caller_ctx, JSAOTFrame *frame,
                                      JSFunctionBytecode *b, JSValueConst func_obj,
                                      JSValueConst this_obj, int argc,
                                      JSValueConst *argv, JSValue *locals,
                                      JSVarRef **frame_var_refs,
                                      JSValue **parg_buf);
/* The interpreter's full exit sequence, ORDER-CRITICAL: close captured locals
   (close_var_ref dups the live stack value, so this MUST run before the frees),
   then free locals[..sp), then pop the frame. */
JS_EXTERN void JS_AOTFrameLeave(JSContext *ctx, JSAOTFrame *frame, JSFunctionBytecode *b,
                                JSValue *locals, JSValue *sp);
/* Slot the twin writes the "current pc" into before ops that can throw or call —
   cache it once: uint8_t **pcslot = JS_AOTFramePCSlot(frame). */
JS_EXTERN uint8_t **JS_AOTFramePCSlot(JSAOTFrame *frame);
/* Interrupt poll — twins call this on branches, like the interpreter does.
   Returns -1 (exception pending) when the interrupt handler fired. */
JS_EXTERN int JS_AOTPoll(JSContext *ctx);

/* ---- operand access ---------------------------------------------------------------- */
static inline JSAtom JS_AOTAtom(const uint8_t *bc, int off) {
    uint32_t v;
    memcpy(&v, bc + off, 4);
    return (JSAtom)v;
}
JS_EXTERN JSValue JS_AOTCpool(JSFunctionBytecode *b, int idx);         /* borrowed */
JS_EXTERN JSValue JS_AOTVarRefGet(JSVarRef **var_refs, int idx);       /* dup'd    */
JS_EXTERN void JS_AOTVarRefPut(JSContext *ctx, JSVarRef **var_refs, int idx,
                               JSValue v);                             /* consumes */

/* ---- value helpers for inlined fast paths ------------------------------------------ */
static inline JSValue js_aot_int32(int32_t v) { return JS_MKVAL(JS_TAG_INT, v); }
static inline JSValue js_aot_float64(double d) { return __JS_NewFloat64(d); }
static inline JSValue js_aot_bool(int v) { return JS_MKVAL(JS_TAG_BOOL, (v != 0)); }
#define JS_AOT_BOTH_INT(a, b) \
    (JS_VALUE_GET_TAG(a) == JS_TAG_INT && JS_VALUE_GET_TAG(b) == JS_TAG_INT)
#define JS_AOT_BOTH_FLOAT(a, b) \
    (JS_TAG_IS_FLOAT64(JS_VALUE_GET_TAG(a)) && JS_TAG_IS_FLOAT64(JS_VALUE_GET_TAG(b)))
/* Mixed int/float arithmetic dominates three.js matrix code (array literals seed
   INT-tagged 0/1 next to floats) and the interpreter can only route it through
   the generic ToNumeric slow path. Twins inline it: for any int|float operand
   pair the result convention is js_float64, exactly what js_binary_arith_slow's
   float arm produces — bit-exact parity, minus the whole slow-path walk. */
#define JS_AOT_IS_NUM(v) \
    (JS_VALUE_GET_TAG(v) == JS_TAG_INT || JS_TAG_IS_FLOAT64(JS_VALUE_GET_TAG(v)))
#define JS_AOT_NUM(v) \
    (JS_VALUE_GET_TAG(v) == JS_TAG_INT ? (double)JS_VALUE_GET_INT(v) \
                                       : JS_VALUE_GET_FLOAT64(v))

/* ---- opcode helpers -----------------------------------------------------------------
   Bodies are the interpreter case bodies (fast path INCLUDED unless named *Slow —
   tnr-aotc inlines the hottest fast paths itself and calls the *Slow entry only
   from the fallback arm). Convention: `psp` points at the live stack-top pointer;
   helpers adjust it exactly like the case body adjusts `sp`. Return 0 ok / -1
   exception (JSValue-returning ones use JS_IsException). `next_pc` = pointer to
   the byte AFTER the instruction in the runtime byte stream. */

/* arithmetic / logic — slow arms (fast paths inlined by the generator) */
JS_EXTERN int JS_AOTOpAddSlow(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                              const uint8_t *next_pc);
JS_EXTERN int JS_AOTOpArithSlow(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                                const uint8_t *next_pc, int op); /* sub..pow */
JS_EXTERN int JS_AOTOpUnarySlow(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                                const uint8_t *next_pc, int op); /* neg/plus/inc/dec */
JS_EXTERN int JS_AOTOpNotSlow(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                              const uint8_t *next_pc);
JS_EXTERN int JS_AOTOpLogicSlow(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                                const uint8_t *next_pc, int op); /* and/or/xor/shl/sar */
JS_EXTERN int JS_AOTOpShrSlow(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                              const uint8_t *next_pc);
JS_EXTERN int JS_AOTOpCmpSlow(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                              const uint8_t *next_pc, int op); /* lt/lte/gt/gte/eq/neq/strict_(n)eq */
JS_EXTERN int JS_AOTOpPostIncDec(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                                 const uint8_t *next_pc, int op); /* full body */
JS_EXTERN int JS_AOTOpIncDecLoc(JSContext *ctx, JSAOTFrame *frame, JSValue *var_buf,
                                int idx, const uint8_t *next_pc, int op); /* inc_loc/dec_loc */
JS_EXTERN int JS_AOTOpAddLoc(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                             JSValue *var_buf, int idx, const uint8_t *next_pc);

/* properties / globals (full bodies incl. fast paths) */
JS_EXTERN int JS_AOTOpGetField(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                               const uint8_t *next_pc, JSAtom atom);
JS_EXTERN int JS_AOTOpGetField2(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                                const uint8_t *next_pc, JSAtom atom);
JS_EXTERN int JS_AOTOpPutField(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                               const uint8_t *next_pc, JSAtom atom);
JS_EXTERN int JS_AOTOpGetArrayEl(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                                 const uint8_t *next_pc);
JS_EXTERN int JS_AOTOpPutArrayEl(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                                 const uint8_t *next_pc);
JS_EXTERN int JS_AOTOpGetVar(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                             const uint8_t *next_pc, JSAtom atom, int undef_ok);
JS_EXTERN int JS_AOTOpPutVar(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                             const uint8_t *next_pc, JSAtom atom, int is_init);

/* calls — cover OP_call/call0..3 (method=0) and OP_call_method (method=1).
   Tail variants return the result through *pret (twin: ret_val = ...; goto done). */
JS_EXTERN int JS_AOTOpCall(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                           const uint8_t *next_pc, int argc, int method);
JS_EXTERN int JS_AOTOpTailCall(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                               const uint8_t *next_pc, int argc, int method,
                               JSValue *pret);
JS_EXTERN int JS_AOTOpCallCtor(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                               const uint8_t *next_pc, int argc);

/* misc */
JS_EXTERN int JS_AOTOpFClosure(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                               JSFunctionBytecode *b, int cpool_idx,
                               JSVarRef **var_refs);
JS_EXTERN int JS_AOTOpPushThis(JSContext *ctx, JSValue **psp, JSValueConst this_obj,
                               int is_strict);
JS_EXTERN int JS_AOTOpTypeof(JSContext *ctx, JSValue **psp);
JS_EXTERN int JS_AOTOpInstanceof(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                                 const uint8_t *next_pc);
JS_EXTERN int JS_AOTOpIn(JSContext *ctx, JSAOTFrame *frame, JSValue **psp,
                         const uint8_t *next_pc);
JS_EXTERN int JS_AOTOpObject(JSContext *ctx, JSValue **psp);
JS_EXTERN int JS_AOTOpDefineField(JSContext *ctx, JSValue **psp, JSAtom atom);
JS_EXTERN int JS_AOTOpToBoolFree(JSContext *ctx, JSValue v); /* branch conditions */

/* let/const TDZ family + small tail ops (coverage push). The check ops are the
   hottest twin opcodes in let-heavy code (every loop-counter read), so their hot
   arms are inline here; only the cold TDZ-violation throw is an exported call. */
JS_EXTERN int JS_AOTThrowUninit(JSContext *ctx, JSFunctionBytecode *b, int idx,
                                int is_ref);  /* always returns -1 */
static inline int JS_AOTOpGetLocCheck(JSContext *ctx, JSValue **psp, JSFunctionBytecode *b,
                                      JSValue *var_buf, int idx) {
    if (JS_VALUE_GET_TAG(var_buf[idx]) == JS_TAG_UNINITIALIZED)
        return JS_AOTThrowUninit(ctx, b, idx, 0);
    *(*psp)++ = JS_DupValue(ctx, var_buf[idx]);
    return 0;
}
static inline int JS_AOTOpPutLocCheck(JSContext *ctx, JSValue **psp, JSFunctionBytecode *b,
                                      JSValue *var_buf, int idx) {
    JSValue old;
    if (JS_VALUE_GET_TAG(var_buf[idx]) == JS_TAG_UNINITIALIZED)
        return JS_AOTThrowUninit(ctx, b, idx, 0);
    old = var_buf[idx];
    var_buf[idx] = *--(*psp);
    JS_FreeValue(ctx, old);
    return 0;
}
JS_EXTERN int JS_AOTOpPutLocCheckInit(JSContext *ctx, JSValue **psp, JSValue *var_buf,
                                      int idx);
static inline int JS_AOTOpGetVarRefCheck(JSContext *ctx, JSValue **psp, JSFunctionBytecode *b,
                                         JSVarRef **var_refs, int idx) {
    JSValue v = JS_AOTVarRefGet(var_refs, idx); /* dup'd */
    if (JS_VALUE_GET_TAG(v) == JS_TAG_UNINITIALIZED)
        return JS_AOTThrowUninit(ctx, b, idx, 1);
    *(*psp)++ = v;
    return 0;
}
JS_EXTERN int JS_AOTOpPutVarRefCheck(JSContext *ctx, JSValue **psp, JSFunctionBytecode *b,
                                     JSVarRef **var_refs, int idx, int is_init);
JS_EXTERN void JS_AOTOpCloseLoc(JSContext *ctx, JSAOTFrame *frame, JSFunctionBytecode *b,
                                int idx);
JS_EXTERN int JS_AOTOpSetName(JSContext *ctx, JSValue **psp, JSAtom atom);
JS_EXTERN int JS_AOTOpArrayFrom(JSContext *ctx, JSValue **psp, int argc);
JS_EXTERN void JS_AOTOpTypeofIs(JSContext *ctx, JSValue **psp, int is_function);

#ifdef __cplusplus
}
#endif

#endif /* QUICKJS_AOT_H */
